//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.ExamOrders = new HashSet<ExamOrder>();
        }
    
        public int ClassID { get; set; }
        public string Name { get; set; }
        public Nullable<int> InstituteID { get; set; }
        public Nullable<int> LevelOfEducationInternationalID { get; set; }
    
        public virtual Institute Institute { get; set; }
        public virtual LevelOfEducationInternational LevelOfEducationInternational { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamOrder> ExamOrders { get; set; }
    }
}
