//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class DegreeOfDifficultyToLevel
    {
        public int DegreeOfDifficultyToLevelOfEductionID { get; set; }
        public Nullable<int> DegreeIDFrom { get; set; }
        public Nullable<int> DegreeIDTo { get; set; }
        public Nullable<int> LevelID { get; set; }
    }
}
