//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamCompositionLine
    {
        public long ExamCompositionLineID { get; set; }
        public Nullable<int> ExamOrderID { get; set; }
        public Nullable<int> PositionNr { get; set; }
        public Nullable<long> QuestionID { get; set; }
        public string Question { get; set; }
        public Nullable<long> AnswerToQuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> Value { get; set; }
        public Nullable<int> SortVersionID { get; set; }
    }
}
