//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamDeliveryLine
    {
        public long ExamDeliveryLineID { get; set; }
        public Nullable<int> ExamOrderID { get; set; }
        public Nullable<int> QuestionTypeID { get; set; }
        public Nullable<long> QuestionID { get; set; }
        public string Question { get; set; }
        public Nullable<long> AnswerID { get; set; }
        public string Answer { get; set; }
        public Nullable<int> DegreeOfDifficultyID { get; set; }
        public Nullable<bool> Value { get; set; }
    
        public virtual Answer Answer1 { get; set; }
        public virtual ExamOrder ExamOrder { get; set; }
        public virtual Question Question1 { get; set; }
    }
}
