//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamOrderStatusLog
    {
        public long ExamOrderStatusLogID { get; set; }
        public Nullable<int> ExamOrderID { get; set; }
        public string Date { get; set; }
        public string UserID { get; set; }
        public Nullable<int> ExamOrderStatusID { get; set; }
    
        public virtual ExamOrder ExamOrder { get; set; }
        public virtual ExamOrderStatu ExamOrderStatu { get; set; }
    }
}
