//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamCandidateHeader
    {
        public long ExamCandidateHeaderID { get; set; }
        public Nullable<int> ExamOrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> EvaluationDate { get; set; }
        public Nullable<int> PointsScored { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ExamOrder ExamOrder { get; set; }
    }
}
