//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamOrder()
        {
            this.ExamCandidateHeaders = new HashSet<ExamCandidateHeader>();
            this.ExamCandidateLines = new HashSet<ExamCandidateLine>();
            this.ExamDeliveryLines = new HashSet<ExamDeliveryLine>();
            this.ExamOrderItems = new HashSet<ExamOrderItem>();
            this.ExamOrderShuffleHeaders = new HashSet<ExamOrderShuffleHeader>();
            this.ExamOrderShuffleLines = new HashSet<ExamOrderShuffleLine>();
            this.ExamOrderStatusLogs = new HashSet<ExamOrderStatusLog>();
        }
    
        public int ExamOrderID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserID { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Disclaimer { get; set; }
        public string Instruction { get; set; }
        public Nullable<int> DurationInMinutes { get; set; }
        public string LanguageID { get; set; }
        public Nullable<int> NumberOfSortVersions { get; set; }
        public Nullable<int> DegreeOfDifficultyID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual DegreeOfDifficulty DegreeOfDifficulty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamCandidateHeader> ExamCandidateHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamCandidateLine> ExamCandidateLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamDeliveryLine> ExamDeliveryLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamOrderItem> ExamOrderItems { get; set; }
        public virtual Language Language { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamOrderShuffleHeader> ExamOrderShuffleHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamOrderShuffleLine> ExamOrderShuffleLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamOrderStatusLog> ExamOrderStatusLogs { get; set; }
    }
}
