//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamOrderShuffleHeader
    {
        public long ExamOrderShuffleHeaderID { get; set; }
        public Nullable<int> ExamOrderID { get; set; }
        public Nullable<int> ExamOrderShuffleID { get; set; }
        public Nullable<int> DegreeOfDifficultyID { get; set; }
        public Nullable<int> NumberOfQuestions { get; set; }
    
        public virtual ExamOrder ExamOrder { get; set; }
    }
}
