//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamCandidateLine
    {
        public long ExamCanditateLineID { get; set; }
        public Nullable<int> ExamOrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<long> QuestionID { get; set; }
        public Nullable<long> AnswerID { get; set; }
        public Nullable<bool> Value { get; set; }
    
        public virtual ExamOrder ExamOrder { get; set; }
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
