//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.AnswerToQuestions = new HashSet<AnswerToQuestion>();
            this.ExamCandidateLines = new HashSet<ExamCandidateLine>();
            this.ExamDeliveryLines = new HashSet<ExamDeliveryLine>();
            this.ExamOrderShuffleLines = new HashSet<ExamOrderShuffleLine>();
        }
    
        public long QuestionID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LanguageID { get; set; }
        public string Text { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> DegreeOfDifficultyID { get; set; }
        public Nullable<int> QuestionTypeID { get; set; }
        public Nullable<int> LevelOfEducationInternationalID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerToQuestion> AnswerToQuestions { get; set; }
        public virtual DegreeOfDifficulty DegreeOfDifficulty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamCandidateLine> ExamCandidateLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamDeliveryLine> ExamDeliveryLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamOrderShuffleLine> ExamOrderShuffleLines { get; set; }
        public virtual Language Language { get; set; }
        public virtual LevelOfEducationInternational LevelOfEducationInternational { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
