//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionToSubject
    {
        public long QuestionToSubjectID { get; set; }
        public Nullable<long> QuestionID { get; set; }
        public Nullable<int> SubjectID { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
