//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCandidateExamHeader
    {
        public long ExamCandidateHeaderID { get; set; }
        public Nullable<int> ExamOrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> EvaluationDate { get; set; }
        public Nullable<int> PointsScored { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int Expr1 { get; set; }
        public Nullable<System.DateTime> Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Disclaimer { get; set; }
        public string Instruction { get; set; }
        public Nullable<int> DurationInMinutes { get; set; }
        public string LanguageID { get; set; }
        public Nullable<int> NumberOfSortVersions { get; set; }
        public Nullable<int> DegreeOfDifficultyID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public int Expr4 { get; set; }
        public string Name { get; set; }
        public int ExamStatusID { get; set; }
        public string Expr5 { get; set; }
    }
}
