//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExamResult
    {
        public Nullable<int> ClassID { get; set; }
        public string Class { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> DifficultyExam { get; set; }
        public Nullable<int> ExamOrderID { get; set; }
        public string Name { get; set; }
        public Nullable<int> QuestionTypeID { get; set; }
        public string Expr1 { get; set; }
        public Nullable<long> QuestionID { get; set; }
        public Nullable<int> DifficultyQuestion { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> Value_correct { get; set; }
        public Nullable<int> AnswersGiven { get; set; }
        public int Score { get; set; }
    }
}
